export const FILTER_GROUPS = {
  progressive: {
    label: "Прогрессивные",
    weapons: {
      AR: [
        "M416 No Signal",
        "M416 Zhu Bajie",
        "M416 Trick-or-treat",
        "M416 Phoenix",
        "AUG Neon Dream",
        "AUG Minotaur",
        "AUG Bumper Blaster",
        "AUG G-DRAGON",
        "AKM Santa's Helper",
        "Beryl M762 Azure Dragon",
        "Beryl M762 Medusa",
        "Beryl M762 Gear Head",
        "Beryl M762 Darkest Depths",
        "ACE32 Demon's Touch",
        "ACE32 Demon Hunter",
      ],
      DMR: [
        "SKS Chrono Cannon",
        "SKS Black Tortoise",
        "Mini14 Yule Sleigh",
        "Mini14 Sha Wujing",
        "SLR Buzzkill",
        "SLR Deadly Dollhouse",
        "MK12 Hocus Focus",
        "MK12 Cyber Threat",
        "MK12 Bunny Patrol",
        "Dragunov Rest in Pink",
      ],
      SR: [
        "Kar98k Midnight Menace",
        "Kar98k Tiger Hunter",
        "M24 Sun Wukong",
        "M24 Final Serenade",
        "M24 Over the Rainbow",
        "AWM Faded Ghost",
      ],
      SMG: ["MP5K Winter Eclipse", "MP5K ZERO-G"],
      LMG: ["M249 Cerberus"],
      SHOTGUN: ["S1897 Sun Scorched", "DBS Atlantis"],
      Melee: ["Pan Siren", "Pan Tang Sanzang", "Pan White Tiger"],
    },
  },

  chroma: {
    label: "Хрома",
    weapons: {
      AR: [
        "M416 No Signal (Yellow Black)",
        "M416 No Signal (Purple Charcoal)",
        "M416 Zhu Bajie (Teal Orange)",
        "M416 Zhu Bajie (Magenta Peach)",
        "M416 Trick-or-treat (Green Navy)",
        "AUG Neon Dream (Magenta)",
        "AUG Minotaur (Gray Tan)",
        "AUG Bumper Blaster (Purple Pink)",
        "AUG G-DRAGON (Red)",
        "AKM Santa's Helper (Red Teal)",
        "Beryl M762 Azure Dragon (Teal Gold)",
        "Beryl M762 Medusa (Gold Charcoal)",
        "Beryl M762 Medusa (Gray Purple)",
        "Beryl M762 Gear Head (Gray)",
        "Beryl M762 Darkest Depths (Brown Mint)",
        "ACE32 Demon's Touch (Yellow Teal)",
        "ACE32 Demon Hunter (Midnight Black)",
      ],
      DMR: [
        "SKS Chrono Cannon (Blue Gold)",
        "Mini14 Sha Wujing (Silver)",
        "SLR Buzzkill (Black Gold)",
        "SLR Deadly Dollhouse (Blue Orange)",
        "MK12 Hocus Focus (Pink Yellow)",
        "MK12 Cyber Threat (Khaki Burgundy)",
        "MK12 Bunny Patrol (Purple)",
        "Dragunov Rest in Pink (Teal Pink)",
      ],
      SR: [
        "Kar98k Midnight Menace (Purple Black)",
        "Kar98k Tiger Hunter (Khaki Crimson)",
        "M24 Sun Wukong (Crimson Gold)",
        "M24 Final Serenade (Blue Black)",
        "M24 Over the Rainbow (Blue Black)",
        "AWM Faded Ghost (Mocha Beige)",
      ],
      SMG: [
        "MP5K Winter Eclipse (Red Purple)",
        "MP5K ZERO-G (Crimson Navy)",
        "MP5K ZERO-G (Lime Blue)",
      ],
      LMG: ["M249 Cerberus (Crimson Lime)"],
      SHOTGUN: ["S1897 Sun Scorched (Yellow Purple)"],
      Melee: ["Pan Siren (Pink)", "Pan Tang Sanzang (Teal)", "Pan White Tiger"],
    },
  },

  gloves: {
    label: "Перчатки",
    list: [
      "PGI Title Wraps",
      "Mazarin1k",
      "Ashek",
      "Shroud",
      "Swagger",
      "spajKK",
      "Danucd",
      "BreaK",
      "Hambinooo",
      "Heybox",
      "Duncan Handwraps",
    ],
  },

  hair: {
    label: "Прически",
    list: [
      "Harley Quinn",
      "The Joker",
      "NieR:Automata 9S",
      "NieR:Automata 2B",
      "Nier's Hairstyle",
      "LISA's BLACKPINK",
      "JISOO's BLACKPINK",
      "ROSÉ's BLACKPINK",
      "JENNIE's BLACKPINK",
      "Nier's Hairstyle"
    ],
  },

  characters: {
    label: "Персонажи",
    list: ["Dorian", "Hanna"],
  },

  makeup: {
    label: "Макияж",
    list: [
      "La Catrina Makeup",
      "Harley Quinn Makeup",
      "The Joker Makeup",
      "Midnight Ritual",
      "Marigold Mayhem",
      "Deadman's Rhythm",
    ],
  },

  cars: {
    label: "Машины",
    list: [
      "Cayenne Turbo GT",
      "911 Carrera GTS",
      "Panamera Turbo S",
      "Chiron",
      "Countach",
      "Urus S",
      "Urus S (Lusso)",
      "Vantage Roadster",
      "DBX707",
      "McLaren GT",
      "Panigale V4 S",
    ],
  },

  smoke: {
    label: "Цвет дыма",
    list: [
      "Pink",
      "Yellow",
      "Emerald",
      "Magenta",
      "Blue",
      "Coral",
      "Teal",
      "Azure",
      "Purple",
      "Orange",
    ],
  },

  survival: {
    label: "Survival Level",
    list: ["1 TIER", "2 TIER", "3 TIER", "4 TIER", "5 TIER"],
  },

  pubgPlus: {
    label: "PUBG PLUS",
    list: ["YES", "NO"],
  },
};
